/**
 * Services configuration for the medical website
 */

export const services = [
  {
    id: "eye-exam",
    title: "Comprehensive Eye Examination",
    description:
      "Complete evaluation of your eye health using state-of-the-art equipment",
    duration: "45 mins",
    price: "$100",
    icon: "🔍",
    featured: true,
    details: [
      "Visual acuity testing",
      "Refraction assessment",
      "Eye pressure measurement",
      "Retinal examination",
      "Corneal evaluation",
    ],
  },
  {
    id: "cataract",
    title: "Cataract Surgery",
    description:
      "Advanced micro-incision cataract surgery with premium lens options",
    duration: "1 hour",
    price: "Consultation required",
    icon: "⚡",
    featured: true,
    details: [
      "Phacoemulsification technique",
      "Premium intraocular lens options",
      "Minimal recovery time",
      "High success rate",
      "Personalized care plan",
    ],
  },
  {
    id: "lasik",
    title: "LASIK Eye Surgery",
    description:
      "Blade-free LASIK for vision correction with advanced technology",
    duration: "30 mins",
    price: "Consultation required",
    icon: "👁️",
    featured: true,
    details: [
      "Wavefront-guided technology",
      "Customized treatment plan",
      "Quick recovery",
      "Reduced dependency on glasses",
      "Long-lasting results",
    ],
  },
  {
    id: "pediatric",
    title: "Pediatric Eye Care",
    description: "Specialized eye care services for children",
    duration: "30 mins",
    price: "$80",
    icon: "👶",
    featured: false,
    details: [
      "Child-friendly examination techniques",
      "Early detection of vision problems",
      "Amblyopia (lazy eye) treatment",
      "Strabismus evaluation",
      "Vision therapy options",
    ],
  },
  {
    id: "glaucoma",
    title: "Glaucoma Treatment",
    description: "Early detection and management of glaucoma",
    duration: "45 mins",
    price: "Varies",
    icon: "💧",
    featured: false,
    details: [
      "Intraocular pressure monitoring",
      "Visual field testing",
      "Optic nerve evaluation",
      "Medication management",
      "Surgical options when necessary",
    ],
  },
  {
    id: "retina",
    title: "Retinal Disorders",
    description: "Diagnosis and treatment of retinal conditions",
    duration: "1 hour",
    price: "Consultation required",
    icon: "🔬",
    featured: false,
    details: [
      "Diabetic retinopathy management",
      "Macular degeneration treatment",
      "Retinal detachment repair",
      "Intravitreal injections",
      "Advanced imaging diagnostics",
    ],
  },
  {
    id: "dry-eye",
    title: "Dry Eye Treatment",
    description: "Relief for chronic dry eye syndrome",
    duration: "30 mins",
    price: "$75",
    icon: "💦",
    featured: false,
    details: [
      "Tear film analysis",
      "Meibomian gland evaluation",
      "Prescription eye drops",
      "Punctal plugs",
      "Lifestyle modification advice",
    ],
  },
  {
    id: "cornea",
    title: "Corneal Transplantation",
    description: "Advanced corneal procedures for vision restoration",
    duration: "2 hours",
    price: "Consultation required",
    icon: "🔄",
    featured: false,
    details: [
      "Full-thickness transplants",
      "DSEK/DMEK procedures",
      "Keratoconus management",
      "Corneal crosslinking",
      "Post-operative care",
    ],
  },
];
